name: Modelops deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:
    types: [ml_ci_cd]
jobs:
  ml_ci_cd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: python version
      run: python --version
      #Diapositiva 3 
    - name: pip install
      run: pip install -r requirements.txt
      #Diapositiva 6
    - name: train model
      run: python model/train.py
      #Diapositiva 7
      

    
